### ISSUE TITLE
非全屏的时候无法长按么

### ISSUE THREAD

**Issue by hoperce** [yate1996/YYStock#11]
如题

**Comment by WillkYang** [comment]
这个是自行设置的，你可以在[YYStockDemoTableViewController.m](https://github.com/yate1996/YYStock/blob/master/YYStockDemo/YYStockDemo/YYStockDemoTableViewController.m)中168行在
```
- (IBAction)stock_exitFullScreen:(id)sender
```
退出全屏的方法中注释关闭响应的代码
```
[self.stock.containerView.subviews setValue:@0 forKeyPath:@"userInteractionEnabled"];
```

**Comment by hoperce** [comment]
thk.
