### ISSUE TITLE
iOS 13 缩放时会出现下图这种情况，请问怎么解决？急！！！

### ISSUE THREAD

**Issue by Marco-1005** [yate1996/YYStock#30]
iOS 13 缩放时会出现下图这种情况，请问怎么解决？急！！！
![image](https://user-images.githubusercontent.com/58931904/70968680-db24d080-20d4-11ea-9334-a6fe4a011649.png)

**Comment by qq826075241** [comment]
我也出现了，有解决办法吗？

**Comment by WillkYang** [comment]
参考一下[YYKline](https://github.com/WillkYang/YYKline)的项目？
